# Generated by Django 2.2.5 on 2019-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_item',
            name='image',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='news_item',
            name='source',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='news_item',
            name='title',
            field=models.CharField(max_length=1024),
        ),
    ]
