# Generated by Django 2.2.5 on 2019-09-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20190904_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_item',
            new_name='news_entry',
        ),
    ]
