# Generated by Django 2.2.5 on 2019-09-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190904_1302'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news_entry',
            table='news_entry',
        ),
    ]
