# Generated by Django 2.2.5 on 2019-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20190905_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.IntegerField(),
        ),
    ]
