# Generated by Django 2.2.5 on 2019-09-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20190905_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name2',
            new_name='short_name',
        ),
        migrations.AddField(
            model_name='team',
            name='full_en_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
