# Generated by Django 2.2.5 on 2019-09-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20190905_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
