# Generated by Django 2.2.5 on 2019-09-05 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20190905_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('published', models.DateTimeField()),
                ('source', models.CharField(max_length=2048)),
                ('image', models.CharField(max_length=2048)),
                ('content_raw', models.TextField()),
                ('content_display', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.News')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team')),
            ],
            options={
                'db_table': 'relationship',
            },
        ),
        migrations.DeleteModel(
            name='news_entry',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team'),
        ),
    ]
