# Generated by Django 2.2.5 on 2019-09-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20190907_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_display',
            field=models.TextField(verbose_name='内容（分段）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_raw',
            field=models.TextField(verbose_name='内容（不分段）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(verbose_name='配图地址'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(verbose_name='原始发布时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=255, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(verbose_name='抓取源 URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='word_count',
            field=models.IntegerField(verbose_name='词数统计'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='area',
            field=models.CharField(max_length=255, verbose_name='赛区'),
        ),
        migrations.AlterField(
            model_name='team',
            name='arena',
            field=models.CharField(max_length=255, verbose_name='主场'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_en_name',
            field=models.CharField(max_length=255, verbose_name='英文全称'),
        ),
        migrations.AlterField(
            model_name='team',
            name='full_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='全称'),
        ),
        migrations.AlterField(
            model_name='team',
            name='joined',
            field=models.CharField(max_length=255, verbose_name='加入 NBA 时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=255, verbose_name='简称'),
        ),
    ]
