# Generated by Django 2.2.5 on 2019-09-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_auto_20190907_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_display',
            field=models.TextField(verbose_name='文章内容（已分段）'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_raw',
            field=models.TextField(verbose_name='原始内容'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team', verbose_name='所属球队'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Team'),
        ),
    ]
